export const ADD_TO_CART = 'ADD_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'





export const SUCCESS_GET_LISTS = 'SUCCESS_GET_LISTS'
export const FAILURE_GET_LISTS = 'FAILURE_GET_LISTS'

